name: Update RSS Feeds

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: github-pages
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install feedgenerator requests beautifulsoup4
      
      - name: Run scraper
        run: python main.py
      
      - name: Commit and push feeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feeds/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update RSS feeds"
          git push

